name: Update Package

on:
  push:
    branches:
      - main # Kütüphanenin ana dalı, isteğe bağlı olarak değiştirilebilir

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12' # Kütüphanenin gereksinimlerine göre Node.js sürümünü güncelleyin
          
      - name: Install dependencies
        run: npm ci
        
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}} # GitHub deposundaki bir gizli (secret) ile token'ı kullanarak npm oturumu açın
